<a href="https://colab.research.google.com/github/yys9905/practice_learning/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

머신러닝 : 컴퓨터에게 학습을해 특정 문제를 해결할수 있는 능력을 만드는것

딥러닝 - 머신러닝 기법중 하나(가이드라인이 불필요)

AlphaGo
기존의 머신러닝으로 만들어졌을 경우
- 바둑 두는 법 가이드를 줌
딥러닝으로 만들어졌을 경우
- 컴퓨터가 try 와 error를 통해 터득함

딥러닝으로 사전지식이 별로 없어도 만들수 있게됨

뉴럴네트워크(뇌 신경망)를 이용해 러닝을 진행

딥러닝이 잘하는 분야
1. Image Classification / Object Detection
2. Sequence Data 분석 & 예측 (ex.번역)

머신러닝 종류 
Supervised Learning : 데이터에 정답이 있고 정답 예측 모델을 만들때 사용

Unsupervised Learning : 데이터에 정답이 없을때 분류하게 하는것

Reinforcement Learning : 상과 벌을 이용해 최종 점수를 높이는 방향으로 학습하게 하는것

perceptron
각각의 특징들이 끼치는 영향력(가중치:weight)을 곱해서 더한후 b(bias)를 더함

*a1*x*w1* + *a2*x*w2* +... + *b*

<img src = https://i.ibb.co/DQYs0dr/Perceptron.png>

실제 데이터를 기준으로 오차를 최대한 줄이는 쪽으로 만들어보라고 시키는것.

딥러닝
perceptron에서 중간에 hidden layer을만들어 여러 perceptron들을 거쳐 예측하는것 - nuralnatwork
layer를 여러게 만들면 딥뉴럴 네트워크라 함

<img src=https://i.ibb.co/GV046FH/Neural-Network.png>

feature extraction(특성추출) - 특성들을 추출해서 예측함

<img src=https://i.ibb.co/9WgSkMX/Neural-Network2.png>

h1 = a1w1 + a2w2 + a3w3
? = h1w7 + h2w8

위를 기반으로 오차를 최소화하는 w값을 찾게 만드는것을 머신러닝이라 하고

오차를 구함과 동시에 모델의 정확도를 평가하는 함수를
손실함수(Loss function)이라함

#$ 1\over n$$∑(ŷ-y)^2$

ŷ == 예측값

y == 실제값

제곱을하는 이유는 정수값을 예측할때 씀

-$1\over n$$Σ[ylog(ŷ) + (1 - y)log(1-ŷ)]$

분류나 확률을 예측할때씀

활성함수(Activation Function)

<img src=https://i.ibb.co/hdwTKFC/active-function-removebg-preview.png>

종류

sigmoid

0~1사이의 값으로 나타남

# $1\over 1 + e^{-x}$

<img src=https://i.ibb.co/q98vgWN/desmos-graph.png>

tanh(Hyperbolic tangent)

-1~1사이의 값으로 나타남

#$e^x-e^{-x}\over {e^x+e^{-x}}$

<img src= https://i.ibb.co/pPD0qy0/desmos-graph-1.png>

Rectified Linear Units

양수면 그대로, 음수면 0으로 나타남

<img src = https://i.ibb.co/mtz8PHP/Rectified-Linear-Units.png>

...

활성함수 없이 예측 : 선형적이고 단순한 예측
활성함수 포함한 예측 : 비선형적이고 복잡한 예측가능




#경사 하강법

#새로운 $w_1 <=  w_1 - α{∂E\over{∂w_1}}$

$α{∂E\over{∂w_1}}$ -> w1이 총손실 E에 얼마나 큰 영향을 끼치는지

딥러닝 학습과정
1. w값들을 랜덤으로 찍는다.
2. w값 바탕으로 총손실 E를 계산한다
3. 경사하강으로 새로운 w값을 업데이트한다.
4. 2번과 3번을 반복(총손실E가 더이상 줄어들지 않을때까지.

#local minima

경사하강을 할때 실제 최저점을 찾기 위해 사용
기울기만 빼는것이 아닌 임의의 learning rate(α)를 곱해서 뺌

#learning rate(α) optimizer
(학습 중간중간 learning rate를 어떤식으로 수정할지를 정함)
- Momentum : 가속도를 유지
- AdaGrad : 자주변하는 w는 작게,자주 변하지 않으면 크게
- RMSProp : AdaGrad의 제곱
- AdaDelta : AdaGrad인데 a가 너무 작아져서 학습 안되는걸 방지
- Adam : RMSProp + Momentum

여러개 써보고 모델과 어울리는것을 택해서 씀(보통 Adam)



#텐서가 필요한 이유

x1 x2 x3

w1 w2 w3

가있을때 계산하려면
파이썬 코드를 쓰기 복잡해지고 귀찮아짐

따라서 행렬을 이용하는데 행렬과 비슷하게 쓸수 있는
텐서플로우 코드가 텐서임

In [27]:
#tensorflow 기초
import tensorflow as tf

tensor = tf.constant([3,4,5]) # 숫자, 리스트등을 담는 곳
tensor2 = tf.constant([6,7,8])
print("tensor + tensor2")
print(tensor + tensor2) 
print()

tensor3 = tf.constant([[1,2],
                       [3,4]])
tensor4 = tf.constant([[5,6],
                      [7,8]])
print("tensor3*tensor4")
print(tensor3*tensor4)
print()

#사칙연산 : tf.add()  tf.subtract() tf.divide() tf.multiply
#행렬곱 : tf.matmul()
print("add(tensor,tensor2)")
print(tf.add(tensor, tensor2))
print()
print("matmul(tensor3, tensor4)")
print(tf.matmul(tensor3,tensor4))
print()

print("tf.zeros")
tensor5 = tf.zeros(10)
print(tensor5)

tensor6 = tf.zeros([2,2]) # tensor의 모양 shape(dimension)
print(tensor6)
print()

print("tensor.shape")
print(tensor.shape)
print("tensor3")
print(tensor3.shape)

#cast 자료형 변환
#variable 변형 가능 constant 변형 불가능
w = tf.Variable(1.0) # weight ()안에 초기값 설정
print(w)
print(w.numpy())
w.assign(2)
print(w.numpy())


tensor + tensor2
tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)

tensor3*tensor4
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)

add(tensor,tensor2)
tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)

matmul(tensor3, tensor4)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)

tf.zeros
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)

tensor.shape
(3,)
tensor3
(2, 2)
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
1.0
2.0


In [37]:
#간단한 선형 회귀 예측
import tensorflow as tf

# height = [170, 180, 175, 160]
# size = [260, 270, 265, 255]
height = 170
size = 260

a = tf.Variable(0.1)
b = tf.Variable(0.2)

def lossFunction():
    y_bar = height * a+b
    return tf.square(size - y_bar)

#경사하강법을 이용해 변수를 업데이트 시켜주는것 learning_rate 지정안할시 자동지정
opt = tf.keras.optimizers.Adam(learning_rate=0.1) 

for i in range(300):
    opt.minimize(lossFunction, var_list=[a,b])
    # print(a.numpy(),b.numpy())
print(height*a.numpy()+b.numpy())

260.0000196695328
